[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
indicatif = "0.18.2"
ndarray = "0.16.1"
# quizx = {git = "https://github.com/zxcalc/quizx"}
quizx = {path = "C:\\Users\\mkim3\\Documents\\code\\quizxFork\\quizx"}
rand = "0.9.2"
rand_distr = "0.5.1"
num-complex = "0.4.6"
itertools = "0.14.0"
num = "0.4.3"
clap = { version = "4.6.0", features = ["derive"] }
mimalloc = "0.1.48"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
